"""gen ai module progress

Revision ID: 00c33acbf6a0
Revises: d057350767f2
Create Date: 2026-09-16 02:34:32.818751
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '00c33acbf6a0'
down_revision: str | None = 'd057350767f2'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('module_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('module_slug', sa.String(length=80), nullable=False),
    sa.Column('best_score', sa.Integer(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_id', 'module_slug', name='uq_module_progress')
    )
    with op.batch_alter_table('module_progress', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_module_progress_module_slug'), ['module_slug'], unique=False)
        batch_op.create_index(batch_op.f('ix_module_progress_profile_id'), ['profile_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('module_progress', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_module_progress_profile_id'))
        batch_op.drop_index(batch_op.f('ix_module_progress_module_slug'))

    op.drop_table('module_progress')
    # ### end Alembic commands ###
