"""accounts, organizations and per-account profiles

Revision ID: 249c2cd4246f
Revises: 6b08809de35b
Create Date: 2026-09-15 01:13:53.182883
"""

from collections.abc import Sequence
from datetime import UTC, datetime

import sqlalchemy as sa
from alembic import op

revision: str = '249c2cd4246f'
down_revision: str | None = '6b08809de35b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_accounts_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_accounts_role'), ['role'], unique=False)

    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('domain', sa.String(length=200), nullable=True),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_organizations_domain'), ['domain'], unique=False)
        batch_op.create_index(batch_op.f('ix_organizations_name'), ['name'], unique=False)

    op.create_table('hr_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', name='uq_hr_member_account')
    )
    with op.batch_alter_table('hr_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hr_members_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_hr_members_organization_id'), ['organization_id'], unique=False)

    # --- Profiles become per-account -------------------------------------- #
    #
    # Three deviations from what autogenerate produced, each of which would
    # fail against a table that already has rows:
    #
    #   * account_id is added nullable, backfilled, and only then made NOT
    #     NULL. Autogenerate emitted it NOT NULL with no default, which cannot
    #     succeed on an existing profile.
    #   * The booleans carry a server_default for the same reason.
    #   * The foreign key is named, so the downgrade can drop it. Autogenerate
    #     emitted `drop_constraint(None, ...)` and warned it would fail.

    with op.batch_alter_table("profiles", schema=None) as batch_op:
        batch_op.add_column(sa.Column("account_id", sa.Integer(), nullable=True))
        batch_op.add_column(
            sa.Column(
                "visible_to_recruiters",
                sa.Boolean(),
                nullable=False,
                server_default=sa.false(),
            )
        )
        batch_op.add_column(
            sa.Column(
                "open_to_work", sa.Boolean(), nullable=False, server_default=sa.true()
            )
        )
        batch_op.add_column(sa.Column("location", sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column("phone", sa.String(length=40), nullable=True))

    _adopt_existing_profiles()

    with op.batch_alter_table("profiles", schema=None) as batch_op:
        batch_op.alter_column("account_id", existing_type=sa.Integer(), nullable=False)
        batch_op.create_index(
            batch_op.f("ix_profiles_account_id"), ["account_id"], unique=True
        )
        batch_op.create_foreign_key(
            "fk_profiles_account_id", "accounts", ["account_id"], ["id"]
        )


#: Django's convention for "this account has no usable password". Argon2 never
#: produces a hash shaped like this, so verification can only ever fail — which
#: is what we want: the row exists and owns its data, but nobody can sign in as
#: it until a password is set with scripts/set_password.py.
UNUSABLE_PASSWORD = "!"


def _adopt_existing_profiles() -> None:
    """Give every pre-existing profile an account to belong to.

    The single-user version had no accounts, so its profile and everything
    hanging off it — jobs, applications, résumés, interviews — would be
    orphaned by a bare schema change. Each one gets a student account carrying
    its existing name and email.

    No password is set, because there is none to migrate and inventing one
    would be worse than requiring a reset.
    """
    bind = op.get_bind()
    now = datetime.now(UTC)

    profiles = bind.execute(
        sa.text(
            "SELECT id, full_name, email FROM profiles WHERE account_id IS NULL"
        )
    ).fetchall()

    for profile_id, full_name, email in profiles:
        # A profile with no email still needs a unique, obviously-invalid
        # placeholder: the column is unique, and `.invalid` is reserved by
        # RFC 2606 precisely so it can never collide with a real address.
        address = (email or "").strip().lower() or f"legacy-{profile_id}@invalid"

        existing = bind.execute(
            sa.text("SELECT id FROM accounts WHERE email = :email"),
            {"email": address},
        ).fetchone()

        if existing is not None:
            account_id = existing[0]
        else:
            bind.execute(
                sa.text(
                    "INSERT INTO accounts "
                    "(email, password_hash, role, full_name, is_active, created_at) "
                    "VALUES (:email, :pw, 'student', :name, :active, :created)"
                ),
                {
                    "email": address,
                    "pw": UNUSABLE_PASSWORD,
                    "name": full_name or "",
                    "active": True,
                    "created": now,
                },
            )
            # Read the id back rather than using `inserted_primary_key`, which
            # is only available on an insert() construct, not raw text(). The
            # email is unique, so this is unambiguous on every backend.
            account_id = bind.execute(
                sa.text("SELECT id FROM accounts WHERE email = :email"),
                {"email": address},
            ).scalar_one()

        bind.execute(
            sa.text("UPDATE profiles SET account_id = :aid WHERE id = :pid"),
            {"aid": account_id, "pid": profile_id},
        )

    if profiles:
        print(
            f"  migrated {len(profiles)} profile(s) onto accounts. "
            "Set a password with: python scripts/set_password.py <email>"
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("profiles", schema=None) as batch_op:
        batch_op.drop_constraint("fk_profiles_account_id", type_="foreignkey")
        batch_op.drop_index(batch_op.f("ix_profiles_account_id"))
        batch_op.drop_column('phone')
        batch_op.drop_column('location')
        batch_op.drop_column('open_to_work')
        batch_op.drop_column('visible_to_recruiters')
        batch_op.drop_column('account_id')

    with op.batch_alter_table('hr_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hr_members_organization_id'))
        batch_op.drop_index(batch_op.f('ix_hr_members_account_id'))

    op.drop_table('hr_members')
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organizations_name'))
        batch_op.drop_index(batch_op.f('ix_organizations_domain'))

    op.drop_table('organizations')
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_accounts_role'))
        batch_op.drop_index(batch_op.f('ix_accounts_email'))

    op.drop_table('accounts')
    # ### end Alembic commands ###
