"""initial schema

Revision ID: 7967fbefa544
Revises: 
Create Date: 2026-09-12 03:48:21.526644
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '7967fbefa544'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('company', sa.String(length=200), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('remote', sa.Boolean(), nullable=True),
    sa.Column('seniority', sa.String(length=60), nullable=True),
    sa.Column('salary_min', sa.Integer(), nullable=True),
    sa.Column('salary_max', sa.Integer(), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=True),
    sa.Column('industry', sa.String(length=120), nullable=True),
    sa.Column('company_size', sa.String(length=60), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_kind', sa.String(length=32), nullable=False),
    sa.Column('source_url', sa.String(length=2000), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('extraction_confidence', sa.Float(), nullable=False),
    sa.Column('unverified_fields', sa.JSON(), nullable=False),
    sa.Column('validation_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('headline', sa.String(length=300), nullable=True),
    sa.Column('years_experience', sa.Float(), nullable=False),
    sa.Column('career_goal', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('skill_aliases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alias', sa.String(length=120), nullable=False),
    sa.Column('canonical', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('skill_aliases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_skill_aliases_alias'), ['alias'], unique=True)
        batch_op.create_index(batch_op.f('ix_skill_aliases_canonical'), ['canonical'], unique=False)

    op.create_table('applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('alignment_score', sa.Float(), nullable=True),
    sa.Column('applied_at', sa.DateTime(), nullable=True),
    sa.Column('deadline', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['job_posts.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id')
    )
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_applications_profile_id'), ['profile_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_applications_status'), ['status'], unique=False)

    op.create_table('interview_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['job_posts.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('interview_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_interview_sessions_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_interview_sessions_profile_id'), ['profile_id'], unique=False)

    op.create_table('job_requirements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('necessity', sa.String(length=32), nullable=False),
    sa.Column('min_years', sa.Float(), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['job_posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('job_requirements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_requirements_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_requirements_name'), ['name'], unique=False)

    op.create_table('learning_paths',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('target_skills', sa.JSON(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('learning_paths', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_learning_paths_profile_id'), ['profile_id'], unique=False)

    op.create_table('preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('target_roles', sa.JSON(), nullable=False),
    sa.Column('locations', sa.JSON(), nullable=False),
    sa.Column('remote_ok', sa.Boolean(), nullable=False),
    sa.Column('seniority', sa.String(length=60), nullable=True),
    sa.Column('min_salary', sa.Integer(), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('company_sizes', sa.JSON(), nullable=False),
    sa.Column('industries', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_id')
    )
    op.create_table('profile_skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('proficiency', sa.String(length=32), nullable=False),
    sa.Column('years', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('profile_skills', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_profile_skills_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_profile_skills_profile_id'), ['profile_id'], unique=False)

    op.create_table('resumes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=300), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('ats_score', sa.Float(), nullable=True),
    sa.Column('strengths', sa.JSON(), nullable=True),
    sa.Column('gaps', sa.JSON(), nullable=True),
    sa.Column('analysis_notes', sa.Text(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('resumes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_resumes_profile_id'), ['profile_id'], unique=False)

    op.create_table('interview_turns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('improvements', sa.JSON(), nullable=True),
    sa.Column('probes_skill', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['interview_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('interview_turns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_interview_turns_session_id'), ['session_id'], unique=False)

    op.create_table('learning_steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('path_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('skill', sa.String(length=120), nullable=False),
    sa.Column('estimated_hours', sa.Float(), nullable=False),
    sa.Column('resource_url', sa.String(length=2000), nullable=True),
    sa.Column('proof_of_work', sa.Text(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['path_id'], ['learning_paths.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('learning_steps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_learning_steps_path_id'), ['path_id'], unique=False)

    op.create_table('status_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('from_status', sa.String(length=32), nullable=True),
    sa.Column('to_status', sa.String(length=32), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('status_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_status_events_application_id'), ['application_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_status_events_occurred_at'), ['occurred_at'], unique=False)

    op.create_table('tailored_resumes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('source_resume_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('emphasized_skills', sa.JSON(), nullable=False),
    sa.Column('change_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['job_posts.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.ForeignKeyConstraint(['source_resume_id'], ['resumes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tailored_resumes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tailored_resumes_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tailored_resumes_profile_id'), ['profile_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tailored_resumes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tailored_resumes_profile_id'))
        batch_op.drop_index(batch_op.f('ix_tailored_resumes_job_id'))

    op.drop_table('tailored_resumes')
    with op.batch_alter_table('status_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_status_events_occurred_at'))
        batch_op.drop_index(batch_op.f('ix_status_events_application_id'))

    op.drop_table('status_events')
    with op.batch_alter_table('learning_steps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_learning_steps_path_id'))

    op.drop_table('learning_steps')
    with op.batch_alter_table('interview_turns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_interview_turns_session_id'))

    op.drop_table('interview_turns')
    with op.batch_alter_table('resumes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_resumes_profile_id'))

    op.drop_table('resumes')
    with op.batch_alter_table('profile_skills', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_profile_skills_profile_id'))
        batch_op.drop_index(batch_op.f('ix_profile_skills_name'))

    op.drop_table('profile_skills')
    op.drop_table('preferences')
    with op.batch_alter_table('learning_paths', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_learning_paths_profile_id'))

    op.drop_table('learning_paths')
    with op.batch_alter_table('job_requirements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_requirements_name'))
        batch_op.drop_index(batch_op.f('ix_job_requirements_job_id'))

    op.drop_table('job_requirements')
    with op.batch_alter_table('interview_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_interview_sessions_profile_id'))
        batch_op.drop_index(batch_op.f('ix_interview_sessions_job_id'))

    op.drop_table('interview_sessions')
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_applications_status'))
        batch_op.drop_index(batch_op.f('ix_applications_profile_id'))

    op.drop_table('applications')
    with op.batch_alter_table('skill_aliases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_skill_aliases_canonical'))
        batch_op.drop_index(batch_op.f('ix_skill_aliases_alias'))

    op.drop_table('skill_aliases')
    op.drop_table('profiles')
    op.drop_table('job_posts')
    # ### end Alembic commands ###
