"""job postings and applications

Revision ID: a464c8587a25
Revises: 249c2cd4246f
Create Date: 2026-09-15 02:46:32.994085
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'a464c8587a25'
down_revision: str | None = '249c2cd4246f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_postings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('posted_by_id', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('company_name', sa.String(length=200), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('remote', sa.Boolean(), nullable=True),
    sa.Column('seniority', sa.String(length=60), nullable=True),
    sa.Column('salary_min', sa.Integer(), nullable=True),
    sa.Column('salary_max', sa.Integer(), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=True),
    sa.Column('industry', sa.String(length=120), nullable=True),
    sa.Column('company_size', sa.String(length=60), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('education', sa.String(length=300), nullable=True),
    sa.Column('certifications', sa.JSON(), nullable=False),
    sa.Column('total_years_experience', sa.Float(), nullable=True),
    sa.Column('source_url', sa.String(length=2000), nullable=True),
    sa.Column('extraction_confidence', sa.Float(), nullable=False),
    sa.Column('opens_at', sa.DateTime(), nullable=True),
    sa.Column('closes_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['posted_by_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('job_postings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_postings_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_postings_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_postings_posted_by_id'), ['posted_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_postings_source'), ['source'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_postings_status'), ['status'], unique=False)

    op.create_table('posting_applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('posting_id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('alignment_score', sa.Float(), nullable=True),
    sa.Column('alignment_detail', sa.JSON(), nullable=True),
    sa.Column('cover_note', sa.Text(), nullable=True),
    sa.Column('applied_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['posting_id'], ['job_postings.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('posting_id', 'profile_id', name='uq_application_once')
    )
    with op.batch_alter_table('posting_applications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_posting_applications_applied_at'), ['applied_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_posting_applications_posting_id'), ['posting_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_posting_applications_profile_id'), ['profile_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_posting_applications_status'), ['status'], unique=False)

    op.create_table('posting_requirements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('posting_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('necessity', sa.String(length=32), nullable=False),
    sa.Column('min_years', sa.Float(), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['posting_id'], ['job_postings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('posting_requirements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_posting_requirements_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_posting_requirements_posting_id'), ['posting_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posting_requirements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_posting_requirements_posting_id'))
        batch_op.drop_index(batch_op.f('ix_posting_requirements_name'))

    op.drop_table('posting_requirements')
    with op.batch_alter_table('posting_applications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_posting_applications_status'))
        batch_op.drop_index(batch_op.f('ix_posting_applications_profile_id'))
        batch_op.drop_index(batch_op.f('ix_posting_applications_posting_id'))
        batch_op.drop_index(batch_op.f('ix_posting_applications_applied_at'))

    op.drop_table('posting_applications')
    with op.batch_alter_table('job_postings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_postings_status'))
        batch_op.drop_index(batch_op.f('ix_job_postings_source'))
        batch_op.drop_index(batch_op.f('ix_job_postings_posted_by_id'))
        batch_op.drop_index(batch_op.f('ix_job_postings_organization_id'))
        batch_op.drop_index(batch_op.f('ix_job_postings_created_at'))

    op.drop_table('job_postings')
    # ### end Alembic commands ###
