"""posting status events

Revision ID: c84144e98971
Revises: b9b062dad67d
Create Date: 2026-09-16 05:00:20.661860
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'c84144e98971'
down_revision: str | None = 'b9b062dad67d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posting_status_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('from_status', sa.String(length=32), nullable=True),
    sa.Column('to_status', sa.String(length=32), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['posting_applications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('posting_status_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_posting_status_events_application_id'), ['application_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_posting_status_events_occurred_at'), ['occurred_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posting_status_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_posting_status_events_occurred_at'))
        batch_op.drop_index(batch_op.f('ix_posting_status_events_application_id'))

    op.drop_table('posting_status_events')
    # ### end Alembic commands ###
